[build-system]
requires = ["setuptools>=61.0", "wheel", "numpy==1.26.4"]
build-backend = "setuptools.build_meta"

[project]
name = "picht"
<<<<<<< Updated upstream
<<<<<<< Updated upstream
<<<<<<< Updated upstream
version = "1.1.4"
=======
version = "2.0.0"
>>>>>>> Stashed changes
=======
version = "2.0.0"
>>>>>>> Stashed changes
=======
version = "2.0.0"
>>>>>>> Stashed changes
description = "Electron and ion optics simulation using the Finite Difference Method (FDM)"
readme = "README.md"
requires-python = ">=3.6"
license = "MIT"

authors = [
    {name = "Rishiit Sharma", email = "rishiitsharma@gmail.com"}
]

dependencies = [
    "matplotlib",
    "scipy",
    "numba",
    "mendeleev",
<<<<<<< Updated upstream
=======
    "pyamg",
    "joblib",
    "cadquery",
    "h5py",
    "numpy==1.26.4",
<<<<<<< Updated upstream
<<<<<<< Updated upstream
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Physics",
    "Intended Audience :: Science/Research",
    "Development Status :: 5 - Production/Stable"
]

[project.urls]
Homepage = "https://github.com/rolypolytoy/picht"