[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "picht"
version = "0.1.0"
authors = [
    {name = "Rishiit Sharma", email = "rishiitsharma@gmail.com"}
]
description = "Electron optics simulation library for electron microscopy applications"
readme = "README.md"
requires-python = ">=3.6"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Physics",
    "Intended Audience :: Science/Research",
    "Development Status :: 3 - Alpha",
]
dependencies = [
    "numpy",
    "matplotlib",
    "scipy",
]

[project.urls]
Homepage = "https://github.com/rolypolytoy/picht"
